spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    url: spring.datasource.url=jdbc:h2:file:/Users/vega/dev/boot/h2-demo/src/main/resources/data/employees;AUTO_SERVER=true
    username: SA
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true